customhost = "employee.c6tfdwjposje.us-east-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee"
custombucket = "add-employee123"
customregion = "us-east-1"
